baseurl = "https://oneill.sh"
enableEmoji = false
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "Ben O'Neill"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 4

[params]
description = "A backend-focused developer in the Boston area."

[menu]
  [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "/apps"
  [[menu.main]]
    identifier = "bookmarks"
    name = "Bookmarks"
    url = "/bookmarks"
  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/library"
